"""replace wb dns fields with ozon fields

Revision ID: 0e274147f8d0
Revises: 4f7c8bd7e43f
Create Date: 2026-05-17 22:30:29.809923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e274147f8d0'
down_revision: Union[str, None] = '4f7c8bd7e43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("TRUNCATE TABLE mice, keyboards, monitors, headphones, microphones, mousepads RESTART IDENTITY CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headphones', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('headphones', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('headphones_dns_product_id_key', 'headphones', type_='unique')
    op.create_unique_constraint(None, 'headphones', ['ozon_sku'])
    op.drop_column('headphones', 'dns_url')
    op.drop_column('headphones', 'wb_sku')
    op.drop_column('headphones', 'wb_url')
    op.drop_column('headphones', 'dns_product_id')
    op.add_column('keyboards', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('keyboards', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('keyboards_dns_product_id_key', 'keyboards', type_='unique')
    op.create_unique_constraint(None, 'keyboards', ['ozon_sku'])
    op.drop_column('keyboards', 'wb_url')
    op.drop_column('keyboards', 'dns_product_id')
    op.drop_column('keyboards', 'dns_url')
    op.drop_column('keyboards', 'wb_sku')
    op.add_column('mice', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('mice', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('mice_dns_product_id_key', 'mice', type_='unique')
    op.create_unique_constraint(None, 'mice', ['ozon_sku'])
    op.drop_column('mice', 'dns_url')
    op.drop_column('mice', 'wb_sku')
    op.drop_column('mice', 'wb_url')
    op.drop_column('mice', 'dns_product_id')
    op.add_column('microphones', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('microphones', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('microphones_dns_product_id_key', 'microphones', type_='unique')
    op.create_unique_constraint(None, 'microphones', ['ozon_sku'])
    op.drop_column('microphones', 'dns_url')
    op.drop_column('microphones', 'wb_sku')
    op.drop_column('microphones', 'wb_url')
    op.drop_column('microphones', 'dns_product_id')
    op.add_column('monitors', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('monitors', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('monitors_dns_product_id_key', 'monitors', type_='unique')
    op.create_unique_constraint(None, 'monitors', ['ozon_sku'])
    op.drop_column('monitors', 'dns_url')
    op.drop_column('monitors', 'wb_sku')
    op.drop_column('monitors', 'wb_url')
    op.drop_column('monitors', 'dns_product_id')
    op.add_column('mousepads', sa.Column('ozon_sku', sa.String(), nullable=True))
    op.add_column('mousepads', sa.Column('ozon_url', sa.String(), nullable=True))
    op.drop_constraint('mousepads_dns_product_id_key', 'mousepads', type_='unique')
    op.create_unique_constraint(None, 'mousepads', ['ozon_sku'])
    op.drop_column('mousepads', 'dns_url')
    op.drop_column('mousepads', 'wb_sku')
    op.drop_column('mousepads', 'wb_url')
    op.drop_column('mousepads', 'dns_product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mousepads', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mousepads', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mousepads', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mousepads', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mousepads', type_='unique')
    op.create_unique_constraint('mousepads_dns_product_id_key', 'mousepads', ['dns_product_id'])
    op.drop_column('mousepads', 'ozon_url')
    op.drop_column('mousepads', 'ozon_sku')
    op.add_column('monitors', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monitors', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monitors', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monitors', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monitors', type_='unique')
    op.create_unique_constraint('monitors_dns_product_id_key', 'monitors', ['dns_product_id'])
    op.drop_column('monitors', 'ozon_url')
    op.drop_column('monitors', 'ozon_sku')
    op.add_column('microphones', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphones', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphones', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('microphones', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'microphones', type_='unique')
    op.create_unique_constraint('microphones_dns_product_id_key', 'microphones', ['dns_product_id'])
    op.drop_column('microphones', 'ozon_url')
    op.drop_column('microphones', 'ozon_sku')
    op.add_column('mice', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mice', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mice', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mice', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mice', type_='unique')
    op.create_unique_constraint('mice_dns_product_id_key', 'mice', ['dns_product_id'])
    op.drop_column('mice', 'ozon_url')
    op.drop_column('mice', 'ozon_sku')
    op.add_column('keyboards', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('keyboards', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('keyboards', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('keyboards', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'keyboards', type_='unique')
    op.create_unique_constraint('keyboards_dns_product_id_key', 'keyboards', ['dns_product_id'])
    op.drop_column('keyboards', 'ozon_url')
    op.drop_column('keyboards', 'ozon_sku')
    op.add_column('headphones', sa.Column('dns_product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('headphones', sa.Column('wb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('headphones', sa.Column('wb_sku', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('headphones', sa.Column('dns_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'headphones', type_='unique')
    op.create_unique_constraint('headphones_dns_product_id_key', 'headphones', ['dns_product_id'])
    op.drop_column('headphones', 'ozon_url')
    op.drop_column('headphones', 'ozon_sku')
    # ### end Alembic commands ###
