"""initial tables

Revision ID: 4f7c8bd7e43f
Revises: 
Create Date: 2026-05-04 16:27:04.267953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7c8bd7e43f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headphones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('construction_type', sa.String(), nullable=True),
    sa.Column('connection_types', sa.String(), nullable=True),
    sa.Column('has_microphone', sa.Boolean(), nullable=True),
    sa.Column('noise_cancellation', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_headphones_id'), 'headphones', ['id'], unique=False)
    op.create_table('keyboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('switches', sa.String(), nullable=True),
    sa.Column('board_material', sa.String(), nullable=True),
    sa.Column('form_factor', sa.String(), nullable=True),
    sa.Column('keycap_material', sa.String(), nullable=True),
    sa.Column('keycap_manufacturing', sa.String(), nullable=True),
    sa.Column('connection_types', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_keyboards_id'), 'keyboards', ['id'], unique=False)
    op.create_table('mice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('sensor', sa.String(), nullable=True),
    sa.Column('switches', sa.String(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('connection_types', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_mice_id'), 'mice', ['id'], unique=False)
    op.create_table('microphones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('mic_type', sa.String(), nullable=True),
    sa.Column('directionality', sa.String(), nullable=True),
    sa.Column('connection_types', sa.String(), nullable=True),
    sa.Column('frequency_range', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_microphones_id'), 'microphones', ['id'], unique=False)
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('diagonal_inch', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('refresh_rate_hz', sa.Integer(), nullable=True),
    sa.Column('matrix_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_table('mousepads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('surface_material', sa.String(), nullable=True),
    sa.Column('hardness', sa.String(), nullable=True),
    sa.Column('has_rgb', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dns_product_id', sa.String(), nullable=True),
    sa.Column('wb_sku', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dns_url', sa.String(), nullable=True),
    sa.Column('wb_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dns_product_id')
    )
    op.create_index(op.f('ix_mousepads_id'), 'mousepads', ['id'], unique=False)
    op.create_table('store_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('dns_product_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('store_address', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_availability_id'), 'store_availability', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_availability_id'), table_name='store_availability')
    op.drop_table('store_availability')
    op.drop_index(op.f('ix_mousepads_id'), table_name='mousepads')
    op.drop_table('mousepads')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_microphones_id'), table_name='microphones')
    op.drop_table('microphones')
    op.drop_index(op.f('ix_mice_id'), table_name='mice')
    op.drop_table('mice')
    op.drop_index(op.f('ix_keyboards_id'), table_name='keyboards')
    op.drop_table('keyboards')
    op.drop_index(op.f('ix_headphones_id'), table_name='headphones')
    op.drop_table('headphones')
    # ### end Alembic commands ###
