"""add mouse extended fields

Revision ID: 9c0e7ecfa788
Revises: 0e274147f8d0
Create Date: 2026-05-17 23:11:29.476802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0e7ecfa788'
down_revision: Union[str, None] = '0e274147f8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mice', sa.Column('button_count', sa.Integer(), nullable=True))
    op.add_column('mice', sa.Column('max_dpi', sa.Integer(), nullable=True))
    op.add_column('mice', sa.Column('color', sa.String(), nullable=True))
    op.add_column('mice', sa.Column('form_factor', sa.String(), nullable=True))
    op.add_column('mice', sa.Column('has_rgb', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mice', 'has_rgb')
    op.drop_column('mice', 'form_factor')
    op.drop_column('mice', 'color')
    op.drop_column('mice', 'max_dpi')
    op.drop_column('mice', 'button_count')
    # ### end Alembic commands ###
